### ISSUE TITLE
Crawler doesn't generate anchor in record urls

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#1282]
## Description

Hi, 
I'm indexing this website based on Docusaurus 2 and Redoc for the API docs. Since I moved to the new infra, my search hits for API docs are leading to the correct page, without taking me to the correct header.

## Steps to reproduce

1. Go to [this website](https://docs.talon.one/)
2. Search for `Get user`
3. The first search result's link is `https://docs.talon.one/management-api/` which is not as accurate as it should be, it should be `https://docs.talon.one/management-api/#operation/getUser`.

The record doesn't contain the full url:

```
Record #20 

url: "https://docs.talon.one/management-api/"
url_without_variables: "https://docs.talon.one/management-api/"
url_without_anchor: "https://docs.talon.one/management-api/"  <----
anchor: ""
content: null
content_camel: null
lang: "en"
language: "en"
type: "lvl2"
...
```

My action looks like this:

```js
    {
      indexName: "talon",
      pathsToMatch: ["https://docs.talon.one/management-api/"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl0: {
              selectors: "",
              defaultValue: "Management API reference docs",
            },
            lvl1: ".api-content h1",
            lvl2: ".api-content h2",
            lvl3: ".api-content h3",
            lvl4: ".api-content h4",
            content: ".api-content h2 + div p",
          },
          indexHeadings: {from:1,to:3}
        });
      },
    },
```

The HTML to crawl look like this, so H2 has all the info the Crawler would need, I suppose.

<img width="789" alt="Screenshot 2022-01-24 at 18 11 03" src="https://user-images.githubusercontent.com/28596581/150831079-6119c5c7-3349-4e59-969e-6169f483ed39.png">

What am I doing wrong 🙁 ?

**Comment by ArthurFlageul** [comment]
Sorry to ping you directly @shortcuts, but any clue?

**Comment by shortcuts** [comment]
Hey, 

(I'm off this week so not able to look deeply/no computer)

We changed our way to detect anchors, could you show a snippet of an anchor in your DOM?

It's possible that your text is not a children of your anchor (sibling or other level), so we can't find it

**Comment by philipvollet** [comment]
Also here for the same problem!

**Comment by philipvollet** [comment]
Any update here?

**Comment by shortcuts** [comment]
Hey, all opened issue will be reviewed next week

**Comment by axilleas** [comment]
:wave: just chiming it to say that it would be nice to have some docs about:

> We changed our way to detect anchors

:slightly_smiling_face:

**Comment by shortcuts** [comment]
Update: we found the issue and will do a bit more of testing before pushing it to prod

@axilleas no docs needed for that case, it's a mistake 😬

**Comment by shortcuts** [comment]
Hey there,

A fix has been deployed, feel free to test and give feedbacks :D

**Comment by philipvollet** [comment]
For us, it's still not working? Do we need to recreate the index or something else?

**Comment by shortcuts** [comment]
Hey, what is your appId?

**Comment by ArthurFlageul** [comment]
Works for us, thanks @shortcuts ❤️
