### ISSUE TITLE
'Search by' displayed twice

### ISSUE THREAD

**Issue by seafoox** [algolia/docsearch#161]
With the new "Search by logo", the `"Search by` label is displayed twice.

![image](https://cloud.githubusercontent.com/assets/1101220/21892600/e7ff3964-d8d7-11e6-8d4a-3ebd3454c4d6.png)

That's for instance the case on:
- https://yarnpkg.com/en/docs/
- https://facebook.github.io/react/

**Comment by maxiloc** [comment]
I don't have that both on chrome and firefox

**Comment by AntoinePlu** [comment]
Neither on Safari

**Comment by seafoox** [comment]
Only happens when docsearch.js is in the cache.
So I have the issue on Chrome, but not Safari or Firefox, has it's first time I load the lib on those browsers.

**Comment by maxiloc** [comment]
You probably get a cache version of an old version.
I released a few version before having something that works everywhere, and this was one of the issue.
Can you check that you have 1.4.4 version of the css file on chrome

**Comment by seafoox** [comment]
As you can see on the screenshot below, I have the version 1.4.4 of the css file, but still have the issue. ![image](https://cloud.githubusercontent.com/assets/1101220/21893376/1ddedff0-d8db-11e6-948c-4b7315fe1156.png)

Is it not because of the `.js` file being cached? I just cleared the cache, and now it works as expected. Would it be a way to prevent people to be in the same situation?

**Comment by maxiloc** [comment]
The only thing I see is the js and css not being at the same version.
It's possible that some user got impacted if they load a docsearch during the deploy of the new logo.
But there is nothing we can do about it. When their browser invalidate the cache the file should update
